version: 2

# specify that we only build html
formats: []

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  apt_packages:
    - pandoc
  jobs:
    # Use uv to speed up the build
    # https://docs.readthedocs.io/en/stable/build-customization.html#install-dependencies-with-uv
    pre_create_environment:
      - asdf plugin add uv
      - asdf install uv latest
      - asdf global uv latest
    create_environment:
      - uv venv
    install:
      - uv sync --group docs
    post_install:
      - uv run python scripts/copy_notebooks.py
    build:
      html:
      - uv run sphinx-build -b html docs/source $READTHEDOCS_OUTPUT/html
