
name: Feature request
description: Suggest a new feature or enhancement to an existing feature
labels: [feature 💡]

body:
- type: textarea
  attributes:
    label: Describe the workflow you want to enable
  validations:
    required: true
- type: textarea
  attributes:
    label: Describe your proposed solution
  validations:
    required: true
- type: textarea
  attributes:
    label: Describe alternatives you've considered, if relevant
- type: textarea
  attributes:
    label: Additional context
- type: dropdown
  attributes:
    label: Impact
    description: How would you rate the impact of this feature for you?
    options:
      - Critical (Blocking work)
      - High (Major improvement)
      - Medium (Significant enhancement)
      - Low (Nice to have)
