"""Interaction metadata and helpers."""

from __future__ import annotations

from shapiq.interactions._indices import (
    BGV,
    BII,
    BV,
    CHGV,
    CHII,
    EGV,
    FBII,
    FSII,
    IGV,
    KADDSHAP,
    KSII,
    SGV,
    SII,
    STII,
    SV,
    CardinalInteractionIndex,
    CoMoebius,
    ExtensionalEquality,
    GeneralizedValueIndex,
    InteractionIndex,
    JointSV,
    Moebius,
    RegressionIndex,
    WeightedBII,
    WeightedBV,
)
from shapiq.interactions._iteration import iter_interactions
from shapiq.interactions._types import (
    Interaction,
    InteractionIndexName,
    InteractionOrientation,
    OrderSemantics,
)
from shapiq.interactions._validation import normalize_interaction, validate_interaction_metadata

__all__ = [
    "BGV",
    "BII",
    "BV",
    "CHGV",
    "CHII",
    "EGV",
    "FBII",
    "FSII",
    "IGV",
    "KADDSHAP",
    "KSII",
    "SGV",
    "SII",
    "STII",
    "SV",
    "CardinalInteractionIndex",
    "CoMoebius",
    "ExtensionalEquality",
    "GeneralizedValueIndex",
    "Interaction",
    "InteractionIndex",
    "InteractionIndexName",
    "InteractionOrientation",
    "JointSV",
    "Moebius",
    "OrderSemantics",
    "RegressionIndex",
    "WeightedBII",
    "WeightedBV",
    "iter_interactions",
    "normalize_interaction",
    "validate_interaction_metadata",
]
