game: "AdultCensus"
game_family: "local_xai"
index: "SV"
max_order: 1

game_params:
  model_name: "decision_tree"
  imputer: "conditional"
  x: 0

ground_truth:
  strategy: "compute"
  method: "ExactComputer"

approximators:
  - "KernelSHAP"
  - "PermutationSamplingSV"
  - "StratifiedSamplingSV"
  - "OwenSamplingSV"

budgets:
  - 100
  - 200

seeds:
  - 0
  - 1
  - 2