game: "BikeSharing"
game_family: "local_xai"
index: "FBII"
max_order: 2

game_params:
  # --- Universal Game Control ---
  model_name: "decision_tree"      # Supported ML models: "decision_tree", "random_forest", "gradient_boosting"
  normalize: true                  # Center game values to be 0 for the empty feature set. Recommended: true (except for SOUM)
  verbose: false                   # Enable internal game-level debugging logs. Defaults to false.

  # === Local XAI Game Setup (Active only when game_family: "local_xai") ===
  imputer: "marginal"              # Missing feature handling strategy. Supported: "marginal", "conditional"
  x: 0                             # The specific sample instance index (row index of the dataset) to explain.
  class_to_explain: 1              # [Classification Only] Integer index of the target class probability to explain.

  # === Global XAI Game Setup (Active only when game_family: "global_xai") ===
  # Note: For classification games (e.g., "AdultCensus"), use "accuracy_score" or "cross_entropy".
  # For regression games (e.g., "BikeSharing", "CaliforniaHousing"), use "mean_absolute_error" or "mean_squared_error".
  loss_function: "mean_absolute_error"
  n_samples_eval: 10               # Number of background rows sampled per coalition to shuffle missing features.
  n_samples_empty: 200             # Background dataset sample size used to calculate the base empty-set loss value.

  # === Synthetic Game Setup (Active only when game: "SOUM") ===
  n: 10                            # Dynamically sets the total number of players (features) for the SOUM game.
  n_basis_games: 20                # Number of underlying mathematical unanimity sub-games to combine. Controls complexity.
  min_interaction_size: 1

ground_truth:
  strategy: "compute"
  method: "ExactComputer"

approximators:
  - "RegressionFBII"
  #  - "SPEX"
  #  - "ProxySPEX"
  - "ProxySHAP"
  - "MSRBiased"

budgets:
  - 250
  - 500
  - 1000
  - 5000
  - 10000

seeds:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
  - 10
  - 11
  - 12
  - 13
  - 14
  - 15
  - 16
  - 17
  - 18
  - 19
  - 20
  - 21
  - 22
  - 23
  - 24
  - 25
  - 26
  - 27
  - 28
  - 29