"""Shapley interaction explanations for machine learning models."""

from shapiq.coalitions import CoalitionArray, DenseCoalitionArray
from shapiq.errors import (
    HistoryError,
    InsufficientSamplesError,
    SamplingError,
    SamplingStallWarning,
    UnsupportedGameError,
)
from shapiq.explainers import (
    Approximator,
    EvidenceApproximator,
    ExactExplainer,
    Explainer,
    PermutationSampling,
    Regression,
)
from shapiq.explanations import DenseExplanationArray, ExplanationArray, SparseExplanationArray
from shapiq.games import (
    CallableGame,
    Game,
    LinkFunction,
    MaskedGame,
    MaskedPredictor,
    Masker,
    Model,
    ModelMaskedPredictor,
)
from shapiq.interactions import (
    BGV,
    BII,
    BV,
    CHGV,
    CHII,
    EGV,
    FBII,
    FSII,
    IGV,
    KADDSHAP,
    KSII,
    SGV,
    SII,
    STII,
    SV,
    CardinalInteractionIndex,
    CoMoebius,
    GeneralizedValueIndex,
    Interaction,
    InteractionIndex,
    InteractionIndexName,
    InteractionOrientation,
    JointSV,
    Moebius,
    OrderSemantics,
    RegressionIndex,
    iter_interactions,
    normalize_interaction,
    validate_interaction_metadata,
)
from shapiq.sampling import (
    ApproximationState,
    BanzhafKernelSampler,
    EmptyState,
    PermutationSIISampler,
    PermutationSTIISampler,
    PermutationWalkSampler,
    Sampler,
    SamplingState,
    ShapleyKernelSampler,
    UnitScheduleSampler,
)

try:
    from ._version import __version__
except ImportError:  # pragma: no cover - _version.py is generated at build time
    __version__ = "0.0.0"

__all__ = [
    "BanzhafKernelSampler",
    "BGV",
    "CHGV",
    "CHII",
    "CardinalInteractionIndex",
    "CoMoebius",
    "EGV",
    "FBII",
    "GeneralizedValueIndex",
    "IGV",
    "JointSV",
    "KADDSHAP",
    "KSII",
    "Moebius",
    "SGV",
    "BII",
    "BV",
    "FSII",
    "SII",
    "STII",
    "SV",
    "ApproximationState",
    "Approximator",
    "CallableGame",
    "CoalitionArray",
    "DenseCoalitionArray",
    "DenseExplanationArray",
    "EmptyState",
    "EvidenceApproximator",
    "ExactExplainer",
    "Explainer",
    "ExplanationArray",
    "Game",
    "HistoryError",
    "InsufficientSamplesError",
    "Interaction",
    "InteractionIndex",
    "InteractionIndexName",
    "InteractionOrientation",
    "LinkFunction",
    "MaskedGame",
    "MaskedPredictor",
    "Masker",
    "Model",
    "ModelMaskedPredictor",
    "OrderSemantics",
    "PermutationSIISampler",
    "PermutationSTIISampler",
    "PermutationSampling",
    "PermutationWalkSampler",
    "Regression",
    "RegressionIndex",
    "Sampler",
    "SamplingError",
    "SamplingStallWarning",
    "SamplingState",
    "ShapleyKernelSampler",
    "SparseExplanationArray",
    "UnitScheduleSampler",
    "UnsupportedGameError",
    "__version__",
    "iter_interactions",
    "normalize_interaction",
    "validate_interaction_metadata",
]
